### ISSUE TITLE
Train data missing

### ISSUE THREAD

**Issue by AndreiCComan** [www-Ye/SSR-PU#3]
Hello, I was wondering where I can find the training data.

**Comment by www-Ye** [comment]
The DocRED dataset can be downloaded following the instructions at https://github.com/thunlp/DocRED/tree/master/data

The Re-DocRED dataset can be downloaded following the instructions at https://github.com/tonytan48/Re-DocRED.

The ChemDisGene dataset can be downloaded following the instructions at https://github.com/chanzuckerberg/ChemDisGene.
